# Generated by Django 5.1.5 on 2025-02-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='LessonType',
        ),
    ]
