# Generated by Django 5.1.5 on 2025-02-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0003_lesson_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='score',
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions_amount',
            field=models.IntegerField(default=10),
        ),
    ]
