# Generated by Django 5.1.5 on 2025-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_remove_lesson_score_lesson_questions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='questions_amount',
        ),
    ]
