# Generated by Django 5.1.5 on 2025-02-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='chapter',
        ),
    ]
