# Generated by Django 5.1.5 on 2025-03-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_userprogress_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='student', max_length=50)),
            ],
        ),
    ]
