# Generated by Django 5.1.5 on 2025-02-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lessons', '0001_initial'),
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_wayuunaiki', models.CharField(max_length=200)),
                ('text_spanish', models.CharField(max_length=200)),
                ('is_known', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='word_phrases', to='Tags.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LessonWordPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_phrases', to='Lessons.lesson')),
                ('word_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordPhrases.wordphrase')),
            ],
        ),
    ]
