# Generated by Django 5.1.5 on 2025-02-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordPhrases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonWordPhrase',
        ),
    ]
