# Generated by Django 5.1.5 on 2025-02-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_remove_lesson_score_lesson_questions_amount'),
        ('WordPhrases', '0002_delete_lessonwordphrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordphrase',
            name='tags',
        ),
        migrations.AddField(
            model_name='wordphrase',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lessons.lesson'),
        ),
    ]
