# Generated by Django 5.1.5 on 2025-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordPhrases', '0004_wordphrase_tags_wordphrase_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordphrase',
            name='lesson',
        ),
    ]
