# Generated by Django 5.1.5 on 2025-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('WordPhrases', '0006_alter_wordphrase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordphrase',
            name='tags',
            field=models.ManyToManyField(default=1, related_name='word_phrases', to='Tags.tag'),
        ),
    ]
