# Generated by Django 5.1.5 on 2025-02-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_word_phrases',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
