# Generated by Django 5.1.5 on 2025-02-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_rename_correct_word_phrases_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
