# Generated by Django 5.1.5 on 2025-02-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_questiontype_text'),
        ('WordPhrases', '0003_remove_wordphrase_tags_wordphrase_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WordPhrases.wordphrase'),
        ),
    ]
