# Generated by Django 5.1.5 on 2025-02-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=''),
        ),
    ]
