# Generated by Django 5.1.5 on 2025-02-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
