# Generated by Django 5.1.5 on 2025-02-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_remove_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='testQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Questions.question')),
                ('campo', models.CharField(max_length=50, verbose_name='')),
            ],
            bases=('Questions.question',),
        ),
    ]
