# Generated by Django 5.1.5 on 2025-02-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_testquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testQuestion',
        ),
    ]
