# Generated by Django 5.1.5 on 2025-02-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_delete_testquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
