# Generated by Django 5.1.5 on 2025-02-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_remove_question_correct_answer_and_more'),
        ('WordPhrases', '0005_remove_wordphrase_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.questiontype'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Questions.question')),
                ('word_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordPhrases.wordphrase')),
            ],
        ),
    ]
