# Generated by Django 5.1.5 on 2025-02-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0005_remove_lesson_questions_amount'),
        ('Questions', '0012_alter_question_lesson_alter_questionoption_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='Questions.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Lessons.lesson'),
        ),
    ]
